### ISSUE TITLE
Error: connect

### ISSUE THREAD

**Issue by tihonnsk** [itsKaynine/thailand-post-api#1]
I was trying to work with SDK but today I got  Error: connect ETIMEDOUT 103.43.229.137:80

**Comment by itsKaynine** [comment]
Hi, maybe the server is down or there is a problem with your internet connection. I've tested the demo code today and everything works fine.

However, as of 22nd August 2016 there will be an update to the API which we will have to wait for the changes to come. Here is their announcement message:

> As of 22 August 2016, there will be an upgrade to Trace and Trace Application core system. | Please update the application to its latest version to avoid discontinuous of service.| | IOS | https://itunes.apple.com/th/app/thailand-post-track-trace/id637371355 | | Android | https://play.google.com/store/apps/details?id=com.trackandtrace.lazylist

**Comment by tihonnsk** [comment]
Hi,
Indeed that was temporary problem. Now it works.
Thank you! I hope you will update the module soon.

Regards,
Viktor

**Comment by itsKaynine** [comment]
@tihonnsk You're welcome! The new app has been released so i'll be updating the module asap.

**Comment by itsKaynine** [comment]
@tihonnsk Now working with latest version of API!

**Comment by tihonnsk** [comment]
Great! Thank you!

**Comment by tihonnsk** [comment]
Hi Punnawut,
When trying use API I receive many errors like this:
count= 1 country= EC weight= 200
count= 1 country= CM weight= 200
{ [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
{ [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
count= 1 country= DM weight= 500
count= 1 country= MC weight= 500
{ [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
count= 1 country= DJ weight= 200
{ [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
count= 1 country= CZ weight= 200
count= 1 country= GH weight= 200

What is the reason?

Thanks,
Viktor

**Comment by itsKaynine** [comment]
@tihonnsk Hi, what OS/Node.js version are you using and how frequent are the requests sent? I also suspect that it might be something related to HTTPS since we were using HTTP before the API updates in August.
